### PR TITLE
Update revision of android submodule

### PR DESCRIPTION
**Pull request by aelmahmoudy**

### CODE REVIEW

**Comment by mvdan** [comment]
The commit doesn't say why the current one is wrong. Is this for 2.1.0? In which case, should we re-tag?

**Comment by aelmahmoudy** [comment]
I checked the RepoManifest for all 2.1.0 builds, none had the current commit for 'android' submodule.

Yes, this is for 2.1.0. Please don't (re)tag though, since upstream seems to be still modifying it.

**Comment by mvdan** [comment]
For now I've removed the 2.1.0 tag. I'll merge once we know for sure that this commit is indeed the correct one, and once the commit message is corrected :)

**Comment by mvdan** [comment]
Squash the two commits into one for 2.1.1, please.

**Comment by aelmahmoudy** [comment]
Done. Upstream has release 2.1.1 (212), so I think F-Droid can update the build now.

**Comment by mvdan** [comment]
@krt16s already did it in #14.

**Pull request closed without merging**
