### PR TITLE
Update submodules to 2.6.4 (264) [build#510]

### PR DESCRIPTION
**Pull request by pihug12**
http://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/510/tagBuild/

### CODE REVIEW

**Comment by mvdan** [comment]
Appreciated! Will wait for the F-Droid repo to test-build it before tagging, as usual.

**Comment by numbnut** [comment]
Hey @mvdan,
does something block the new version from being released? Would it be possible to help somehow? Is the test-build result publicly available?

**Comment by mvdan** [comment]
Note that this repo just holds information necessary to build each version. There is more work required to get it to compile and work right, so you should check with the F-Droid people instead of me.

**Comment by numbnut** [comment]
Ok thanks!

**Comment by pihug12** [comment]
@numbnut I saw the build was failing on the droiddata repo (https://gitlab.com/fdroid/fdroiddata/commit/35b3d97f8be4421e4c663a1b61d10d6c909594c6). Maybe @krt16s can provide some more infos.

https://f-droid.org/wiki/page/net.osmand.plus

**Comment by krt16s** [comment]
The build required a username for accessing github, see
https://f-droid.org/wiki/page/net.osmand.plus/lastbuild.
Most likely submodules stuff, but it might ahve been me
doing substiution or something... haven't looked at it.

You should open an issue at fdroiddata issue tracker,
since I am no longer working on F-Droid.

**Pull request merged**
