### PR TITLE
Update submodules to 2.1.1 (212)

### PR DESCRIPTION
**Pull request by krt16s**
Commits from http://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/333/tagBuild/ with a bumped help to include some minor fixes.

Merge, tag, enable build and bump CV at will.

### CODE REVIEW

**Comment by mvdan** [comment]
Are we completely sure this is it? Do we know that they won't do more 2.1.1 releases like last time?

**Comment by krt16s** [comment]
You never know. Maybe just wait a couple of days or even until I am back. I'll use this build on my trip, so it better should be stable ;). 

As I said, I'll leave the decision to you.

**Comment by mvdan** [comment]
It can wait a week, will merge once I'm all settled after my travel next weekend.

**Comment by aelmahmoudy** [comment]
They released to GooglePlay, so I think it is settled.

**Comment by mvdan** [comment]
Fair enough, I'll merge and tag. Thank you both for the help.

**Comment by mvdan** [comment]
Merged and tagged :)

**Pull request merged**
