### PR TITLE
Update submodules to 2.4.6 (246) [build#454]

### PR DESCRIPTION
**Pull request by pihug12**
http://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/454/tagBuild/
http://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/454/console

Changelog since 2.4.4 : https://github.com/osmandapp/Osmand/compare/6416764c7a4a889abc9dbb6542373de9c89e7f3d...237e38547885ffbc9fcfe35a6a96cac348195629

### CODE REVIEW

**Comment by krt16s** [comment]
I tested 2.4.4 and didn't find any mayor issues. I was going to bump our CVC so it gets distributed to non-beta users. Do you recommend to ditch 2.4.4 and wait for this to be done, or should i proceed to push 2.4.4 to users?

**Comment by pihug12** [comment]
No idea. :confused: I didn't build/test any of the 2.4 versions and I don't know the pros & cons for you to push these two versions for the whole community (limit the bandwidth usage?).

**Comment by krt16s** [comment]
Tested it for some days, looks good. @mvdan, tag when ever you are ready.

**Comment by mvdan** [comment]
done.

**Pull request merged**
