### PR TITLE
Update submodules to 2.4.4 (244) [build#445]

### PR DESCRIPTION
**Pull request by pihug12**
http://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/441/tagBuild/
http://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/441/console

### CODE REVIEW

**Comment by mvdan** [comment]
@krt16s I've invited you to have write access to this repo, no need for us to have a back and forth since I'm the only one able to merge and tag.

**Comment by krt16s** [comment]
I will have a look at it tomorrow.

**Comment by krt16s** [comment]
Does not build for me:

````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':OsmAnd:compileFullLegacyFatReleaseJavaWithJavac'.
> Could not expand ZIP '/home/krt/.gradle/caches/modules-2/files-2.1/net.osmand/OsmAndCore_android/0.1-SNAPSHOT/5a3e4bd37100017a0ca1c2e7f281a04715d7368a/OsmAndCore_android-0.1-SNAPSHOT.jar'.
````

Will have to investigate a bit if this is my setup, an fdroid issue or whatever... 

@pihug12: Did you build that with fdroidserver?

**Comment by pihug12** [comment]
I did not and I don't think I have the expected skills to do it. I only thought making this PR would make you gain some time.

@vshcherb suggests to wait for OsmAnd 2.4.4 (https://github.com/osmandapp/Osmand/issues/2953#issuecomment-240225651).

**Comment by yourealwaysbe** [comment]
I was able to build pihug12's version using fdroidserver with no issues.  I have installed it on my phone and it appears to work correctly, but i have not tested it extensively.

**Comment by pihug12** [comment]
@yourealwaysbe @krt16s I updated the PR for 2.4.4.
http://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/445/tagBuild/

**Comment by krt16s** [comment]
I started the build yesterday before going to bed, but it broke due connectivity issues. I'll have  a look at it now. I am currently building the last-known-good build to ensure my setup is correct. After that I will try this PR. Even if it does not build for me, I will most likely merge it, since the commits are obviously the correct ones.

@mvdan: Don't tag a release in any case.  If I merge I'll give the BS a try at building it without bumping CV. If it succeeds, I will dogfood it some days and ping you again for the tag.

**Comment by mvdan** [comment]
@krt16s tags aren't signed, so you can tag just as well as I can.

**Comment by krt16s** [comment]
Managed to build it. Looks like ndk10 is required, ndk11 or ndk12 didn't work out for me. Also I had some weird java8 issues.... and upstream pushed a .swp file to the repo... sigh. Merging. Thanks for the pull request, really appreciated.

**Pull request merged**
